# Named Cloudflare Tunnel
# Example:
#   cloudflared tunnel --config ./tunnels/configs/tunnel_named.yml run

tunnel: 7cccb0e3-ebc4-4ec8-bc5c-90ec034f8115
credentials-file: /home/parkens/.cloudflared/7cccb0e3-ebc4-4ec8-bc5c-90ec034f8115.json

# Network: TCP/h2 & IPv4
protocol: http2
edge-ip-version: 4

# Logs / Metrics
loglevel: info
logfile: ./tunnels/logs/tunnel_named.log   # tunnels/logs
metrics: 127.0.0.1:8081                    # Prometheus

# Disable auto-updates for consistancy
no-autoupdate: true

# Defalt settings for ingress
originRequest:
  connectTimeout: 10s
  tlsTimeout: 10s
  tcpKeepAlive: 30s
  keepAliveConnections: 100
  keepAliveTimeout: 30s
  http2Origin: false
  disableChunkedEncoding: true

ingress:
  # main path: nginx
  - hostname: proxy.ters-team.com
    service: http://localhost:8080

  # healthcheck-host
  - hostname: status.proxy.ters-team.com
    service: http_status:200

  # fallback
  - service: http_status:404
  